### ISSUE TITLE
TypeError: invalid file: None

### ISSUE THREAD

**Issue by tiktuk** [pyexcel/Flask-Excel#12]
The example from the Quick Start works perfectly but when I try to use the get_dict() or get_array() functions when responding to requests made from Flask-Admin, I get the following error:

Here is the traceback: https://gist.github.com/af22b27762543a62709ea89897bc0539 .

I call it from here:

``` python
@pre_save(sender=BulkMessage)
def on_bulk_message_save_handler(model_class, instance, created):
    instance.file_fields = request.get_array(field_name='file')
```

The request object does have the correct file name at the point of calling get_array():

```
dump(request.files)
Contents of werkzeug.datastructures.ImmutableMultiDict object at 0x7fc8e6daf3b8
file    

<FileStorage: 'SMS_dummy_data.xlsx' ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')>
```

But the file contents are lost somewhere in get_array():

```
File "/home/tuk/.virtualenvs/bulksms/lib/python3.4/site-packages/pyexcel_webio/__init__.py", line 93, in get_dict

return pe.get_dict(**params)

[console ready]
>>> dump()
Local variables in frame
params  

{'file_content': b'', 'name_columns_by_row': 0, 'file_type': 'xlsx'}

keywords    

{'name_columns_by_row': True, 'field_name': 'file'}

self    

<ExcelRequest 'http://localhost:5000/admin/bulkmessage/new/?url=%2Fadmin%2Fbulkmessage%2F' [POST]>
```

Any ideas?

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel-webio/blob/master/pyexcel_webio/__init__.py#L197 returns:

    {'file_content': b'', 'name_columns_by_row': 0, 'file_type': 'xlsx'}

Hence, it means request.files['file'].read() == "", empty file was uploaded.

Here's how I upload a file programmatically https://github.com/pyexcel/Flask-Excel/blob/master/tests/test_upload_n_download_excel.py#L36

Here's how I upload file using html form https://github.com/pyexcel/Flask-Excel/blob/master/examples/tiny_example.py#L19

**Comment by chfw** [comment]
And what you can test is:

    @pre_save(sender=BulkMessage)
    def on_bulk_message_save_handler(model_class, instance, created):
        import pdb;pdb.set_trace()
        print(request.files['file'].read())
        instance.file_fields = request.get_array(field_name='file')

**Comment by tiktuk** [comment]
Yeah, the strange thing is that the file is in fact uploaded every time.

And it looks correct here in the request:

```
>>> request.files
ImmutableMultiDict([('file', <FileStorage: 'SMS_dummy_data.xlsx' ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')>)])
```

But it's true that I can't read() it:

```
>>> print(request.files['file'].read())                                              
b''
```

But why is it correctly uploaded then? I'm sure this is some basic Flask noob mistake. Probably not anything wrong with your library.

**Comment by tiktuk** [comment]
Oh yeah, the tiny example works perfectly.

**Comment by chfw** [comment]
Just in case we may have skipped this line: 

    <form .. enctype=multipart/form-data>

according to [Flask documentation](http://flask.pocoo.org/docs/0.10/patterns/fileuploads/)

**Comment by tiktuk** [comment]
That line is generated by the FileUploadField from Flask-Admin. And I do in fact see the file contents in the request in Firefox' inspector. And it does get uploaded. Really weird,

**Comment by chfw** [comment]
It was found in https://github.com/pyexcel/pyexcel/issues/67 that the upload file stream could have been consumed. Maybe a file.seek(0) could help.
