### ISSUE TITLE
How to ignore blank lines with flask-excel when import from xlsx?

### ISSUE THREAD

**Issue by yaoelvon** [pyexcel/Flask-Excel#13]
I used flask-excel to import data from xlsx file. When blank lines exist in xlsx file, pyexcel gives '' for empty cell and inserts '' in every row into database. When I have a row unique, code will raise error.

Is there a simple way to ignore blank lines? Thanks.

**Comment by chfw** [comment]
You would need to apply a custom filter. At the moment, what you can do is to obtain a sheet instance via [get_sheet](http://flask-excel.readthedocs.io/en/latest/#flask_excel.ExcelRequest.get_sheet). Then you can do the following:

    >>> import pyexcel as pe
    >>> sheet = pe.Sheet([[1,2,3],['','',''],['','',''],[1,2,3]])
    >>> sheet
    pyexcel sheet:
    +---+---+---+
    | 1 | 2 | 3 |
    +---+---+---+
    +---+---+---+
    +---+---+---+
    | 1 | 2 | 3 |
    +---+---+---+
    >>> def filter_row(row):
    ...     result = [element for element in row if element != '']
    ...     return len(result)==0
    ...
    >>> sheet.apply_filter(pe.RowValueFilter(filter_row))
    >>> sheet
    pyexcel sheet:
    +---+---+---+
    | 1 | 2 | 3 |
    +---+---+---+
    | 1 | 2 | 3 |
    +---+---+---+

**Comment by yaoelvon** [comment]
Thanks, the following is my way:
```
excel_data = request.get_records(field_name='file')
not_null_line_data = []
for d in excel_data:
    if all(map(lambda x: x == '', d.values())):
        continue
    not_null_line_data.append(d)
````

**Comment by yaoelvon** [comment]
![image](https://cloud.githubusercontent.com/assets/15225634/15889206/ca81f156-2d9c-11e6-94d1-e5f4e7949aa5.png)
something is wrong...

**Comment by chfw** [comment]
Oh... my fault. It should be 'filter' instead of 'apply_filter', which does not exist

**Comment by yaoelvon** [comment]
Thank you very much. I get it!

**Comment by vaishalichaudhari** [comment]
How can do it with:
 excel_data = request.get_book_dict(field_name='file')

**Comment by vaishalichaudhari** [comment]
Is it possible to filter with get_book_dict? 
I have following file with 11 sheets
[Orange-CERT-CC-IOC-PETYA-v1.5.xlsx](https://github.com/pyexcel-webwares/Flask-Excel/files/1951674/Orange-CERT-CC-IOC-PETYA-v1.5.xlsx)

**Comment by vaishalichaudhari** [comment]
or can you please elaborate:     book['Sheet1'].filter(...)

**Comment by chfw** [comment]
this issue has been a while and the api has changed since.  I am starting to forget things.

The simplest way is:

```
excel_data = request.get_book_dict(field_name='file', skip_empty_row=True)
```

However, if your sheet data have white spaces, you will need the following solution:

```
def filter_empty_row(row_index, row_content):
    empty_row = [element for element in row_content if element.strip() != '']
    return len(emtpy_row)  # delete it if True

book = request.get_book(field_name='file')
for sheet in book:
    del sheet.row[filter_empty_row]  # delete the empty lines 
```

And now we can collapse all code in a simpler form:

```
book = request.get_book(field_name='file')
for sheet in book:
    del sheet.row[lambda _, row: len([element for element in row if row.strip() != '']) == 0]
```

**Comment by vaishalichaudhari** [comment]
Thank you so much for a solution

**Comment by chfw** [comment]
It is my pleasure!
