### ISSUE TITLE
Return Book

### ISSUE THREAD

**Issue by adityosnrost** [pyexcel/Flask-Excel#14]
Hi, I'm just trying pyexcel for creating xls file using python. I have created book data. But when I was trying to make response with make_response_from_array, the return file to client was not multi sheet / book ? is there anything that wrong with my simple example ? This is my example code:

`#Get Campaigns Blocking by HTTP GET
@app.route('/xlsheet', methods=['GET'])
def xlsheet():

    two_dimensional_array = [
    	[1,2,3,4,5],
    	[6,7,8,9,0],
    	[11,22,23,12,33]
    ]

    multi = {
    	'Sheet 1': [
    		['a',1],
    		['b',2],
    		['c',3]
    	],
    	'Sheet 2': [
    		['a',1],
    		['b',2],
    		['c',3]
    	],
    	'Sheet 3': [
    		['a',1],
    		['b',2],
    		['c',3]
    	],

    }

    #sheet = pe.Sheet(two_dimensional_array)
    #sheet.save_as("/home/adsback/QAA-API/output1.xls")

    #book = pe.get_book(bookdict=multi)
    #book.save_as("/home/adsback/QAA-API/output2.xls")

    return fe.make_response_from_array(multi, "xls", file_name="export_data")`

**Comment by adityosnrost** [comment]
Halooo, sorry, I've just found it hahaha, sorry for making useless issue haha, I've missed the making response on documentation. It should be:

return fe.make _response_from_book_dict()

Cheers :D

**Comment by chfw** [comment]
Here is [a table of data structure to method mapping](http://flask-excel.readthedocs.io/en/latest/#all-supported-data-types).  So what you need to use is to call [make_response_from_book_dict](http://flask-excel.readthedocs.io/en/latest/#flask_excel.make_response_from_book_dict)
