### ISSUE TITLE
Importing flask.ext.excel is deprecated, use flask_excel instead

### ISSUE THREAD

**Issue by mygethub-99** [pyexcel/Flask-Excel#17]
from flask.ext import excel is throwing an error.  ExtDeprecationWarning: Importing flask.ext.excel is deprecated, use flask_excel instead.
  .format(x=modname), ExtDeprecationWarning

**Comment by chfw** [comment]
Will fix this. Wasn't made aware of the new release 0.11.x until this issue.

**Comment by mygethub-99** [comment]
Thank you! :)
