### ISSUE TITLE
Flask-Excel did not work in my Ubuntu server

### ISSUE THREAD

**Issue by Pinsonbavard** [pyexcel/Flask-Excel#18]
When I did 

**pip install Flask-Excel** 

on Windows, it worked as expected but when I did same on my Linux server, it did not.

I can the installed packages pyexcel_webio and others, but it did not work.

**Comment by chfw** [comment]
All tests of Flask-Excel are performed under travis-ci in linux instances. I am not sure about your setup.

**Comment by chfw** [comment]
Just realized that unless you are having a python version that this library wasn't tested against. The tested python versions are listed [here](https://github.com/pyexcel/Flask-Excel/blob/master/.travis.yml#L5). What do you have there?

**Comment by chfw** [comment]
Please re-open the issue when more details are available.
