### ISSUE TITLE
I hope  name sheet function can be added

### ISSUE THREAD

**Issue by luis-allan** [pyexcel/Flask-Excel#19]
I found there is no params to name a sheet in a excel file

**Comment by chfw** [comment]
Surely, it can be added. Can you share a bit more on how you want it? Add a parameter 'sheet_name' in make_response methods?

**Comment by luis-allan** [comment]
@chfw if only one sheet supported, add a parameter 'sheet_name' there is the best way, it can meet my demands perfect. Thanks

**Comment by chfw** [comment]
released via pyexcel v0.4.0 and pyexce-webio v0.0.9. Here is an usage example: https://github.com/pyexcel/pyexcel-webio/blob/master/tests/test_webio.py#L246
