### ISSUE TITLE
will not import

### ISSUE THREAD

**Issue by veames** [pyexcel/Flask-Excel#20]
Hi, I've installed Flask Excel via pip, no problem within my virtualenv.

I see it 
```
pip list
Flask (0.11.1)
Flask-Excel (0.0.5)

```
But when I add
`import flask_excel as excel`
I get 
`ImportError: No module named flask_excel`

**Comment by chfw** [comment]
Try quit your virtualenv and do pip list again. If you stilll see Flask-Excel, uninstall it. Then activate your virtualenv and do pip list.

**Comment by veames** [comment]
Thanks, something strange was up with my virtualenv settings. I deleted the ~/project/virt-env directory and rebuilt it, working fine now thanks, can't wait to play with it.
