### ISSUE TITLE
Multiple sheets?

### ISSUE THREAD

**Issue by bustawin** [pyexcel/Flask-Excel#21]
Is it possible to have different sheets? I cannot find any example / documentation that says so.

Thanks and congratulations for the extensions.

**Comment by chfw** [comment]
yes, pyexcel.Book can hold multiple sheets. You can read these:

http://pyexcel.readthedocs.io/en/latest/api.html#book

http://flask-excel.readthedocs.io/en/latest/#all-supported-data-types

**Comment by bustawin** [comment]
Really thanks. 
There is not a link to `http://flask-excel.readthedocs.io` from the readme.rst, isn't? It can be that I am too blind, too :-). I arrived to extension through github and I was not aware of the `flask-excel.readthedocs.io`.

**Comment by misilot** [comment]
@bustawin were you able to figure how to create a book and add multiple sheets to it?

I'm trying to create an excel file that has multiple sheets, to generate a report.
