### ISSUE TITLE
import is success , But the  Data is not stored

### ISSUE THREAD

**Issue by laolu94678** [pyexcel/Flask-Excel#26]
import is success , and it return "Saved" ,But the  Data is not stored , I think something is wrong ,but don't konw  where..

![image](https://user-images.githubusercontent.com/12753356/29003985-4922ef84-7af3-11e7-8e5f-a16f95b43872.png)
![image](https://user-images.githubusercontent.com/12753356/29003990-592672a2-7af3-11e7-8f9b-e5f1b8920b59.png)
![image](https://user-images.githubusercontent.com/12753356/29003993-5eddcab0-7af3-11e7-86f0-f6b0fba74d05.png)
![image](https://user-images.githubusercontent.com/12753356/29003999-698cd0dc-7af3-11e7-8f94-1beb0d6f2ebe.png)
127.0.0.1 - - [06/Aug/2017 22:05:35] "[37mPOST /import HTTP/1.1[0m" 200 -

**Comment by chfw** [comment]
Your bug report is appreciated. It is a showstopper and was under the radar for a long time I guess. It is a reputation-saver. 

The change else(pyexcel-io) was that the sample-data.xls should have its sheet name match the database name. Sheet 'post' -> Post table, Sheet 'category' -> Category table.

**Comment by laolu94678** [comment]
Thanks for your reply.
I would like to know how to upload any excel  and store it in my database.I can know all the tables I have uploaded so that I can retrieve it according to my needs

**Comment by chfw** [comment]
I understand your use case that you would like to import any excel sheet without pre-defining any database tables. However, pyexcel family has weak support for databases. I will find a time slot to write a strong import functions that does automatic database import. Please watch this project for further updates.
