### ISSUE TITLE
Version on pip not the latest one

### ISSUE THREAD

**Issue by joyalexandre** [pyexcel/Flask-Excel#9]
When we do `pip install Flask-Excel` the version installed is 0.0.4.

On https://pypi.python.org/pypi they only have the 0.0.4 version.

I'm not sure if it's related, but when we do a
`from flask.ext import excel`
or
`import flask.ext.excel`

We have a warning that _excel_ is an unresolved reference.

**Comment by chfw** [comment]
0.0.4 is the latest from Flask-Excel. 0.0.5 is the next release candidate but it didn't had new features nor bug fix to release. All changes since 0.0.4 were from house keeping backlogs. 

Are you using pycharm?

**Comment by joyalexandre** [comment]
Yes I'm using pyCharm.

**Comment by chfw** [comment]
I think pycharm may have interpreter in its setting and that interpreter envionment(or virtual environment) decides if it is resolved reference or not. 

Here are a few pointers for you:
https://www.jetbrains.com/pycharm/help/resolving-references.html
http://stackoverflow.com/questions/21236824/unresolved-reference-issue-in-pycharm
